# Generated by Django 5.2 on 2025-06-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('locations', '0003_load_initial_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='locations.district'),
        ),
        migrations.AddField(
            model_name='institution',
            name='ds_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='locations.dsdivision'),
        ),
    ]
