# Generated by Django 5.2 on 2025-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_district_institution_ds_division'),
    ]

    operations = [
       
       
       
    ]
