# Generated by Django 5.2 on 2025-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_address_en_institution_address_si_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
