# Generated by Django 5.2 on 2025-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_institution_description'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='institution',
            name='google_map_link',
            field=models.URLField(max_length=500),
        ),
    ]
