# Generated by Django 5.2 on 2025-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institution_address_en_institution_address_si_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='address_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='description_si',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='head_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='head_name_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='head_position_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='head_position_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_si',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='description_si',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='name_si',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
