# Generated by Django 5.2 on 2025-06-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('locations', '0003_load_initial_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
