# Generated by Django 5.2 on 2025-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('minister', 'Minister of Education'), ('deputy', 'Deputy Minister'), ('director', 'Director General'), ('management', 'Top Management')], max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='board_members/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
