# Generated by Django 5.2 on 2025-06-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "aboutus",
            "0003_boardmember_department_en_boardmember_department_si_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
            ],
        ),
    ]
