# Generated by Django 5.2 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_load_initial_locations'),
    ]

    operations = [
    ]
