# Generated by Django 5.2 on 2025-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_load_initial_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dsdivision',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dsdivision',
            name='name_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='province',
            name='name_si',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
