# Generated by Django 5.2 on 2025-05-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_backgrounds/'),
        ),
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.JSONField(default=list, help_text="Structured content in format [{'title': 'Module 1', 'topics': ['Topic 1', 'Topic 2']}]"),
        ),
        migrations.AddField(
            model_name='course',
            name='districts',
            field=models.JSONField(default=list, help_text='List of available districts for this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='features',
            field=models.JSONField(default=list, help_text='List of course features'),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.JSONField(default=list, help_text='List of entry qualifications'),
        ),
    ]
