# Generated by Django 5.2 on 2025-06-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_dashboardstat_service_popularcourse'),
        ('institutions', '0001_initial'),
        ('locations', '0003_load_initial_locations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='districts',
        ),
        migrations.AddField(
            model_name='course',
            name='available_districts',
            field=models.ManyToManyField(blank=True, related_name='courses', to='locations.district'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='institution',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__in': ['DISTRICT', 'NATIONAL']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.trainingcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'institution', 'start_date', 'schedule')},
        ),
    ]
