# Generated by Django 5.2 on 2025-06-07 14:44

from django.db import migrations

def migrate_training_centers_to_institutions(apps, schema_editor):
    TrainingCenter = apps.get_model('courses', 'TrainingCenter')
    Institution = apps.get_model('institutions', 'Institution')
    CourseOffering = apps.get_model('courses', 'CourseOffering')
    
    # Create institutions for each training center
    for center in TrainingCenter.objects.all():
        institution, created = Institution.objects.get_or_create(
            name=center.name,
            defaults={
                'type': 'DISTRICT',
                'city': center.location,
                'address': center.address,
                'email': center.email,
                'phone1': center.contact_number,
                'google_map_link': center.google_map_link or '',
                'is_active': True
            }
        )
        # Update related course offerings
        CourseOffering.objects.filter(center=center).update(institution=institution)

def reverse_migration(apps, schema_editor):
    # We'll set institution back to NULL if we need to reverse
    CourseOffering = apps.get_model('courses', 'CourseOffering')
    CourseOffering.objects.all().update(institution=None)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseoffering_unique_together_and_more'),
        ('institutions', '0001_initial'),  # Ensure institutions app is migrated first
    ]

    operations = [
         migrations.RunPython(migrate_training_centers_to_institutions, reverse_migration),
    ]
