# Generated by Django 5.2 on 2025-06-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_migrate_training_centers'),
        ('institutions', '0002_institution_district_institution_ds_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='center',
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='institution',
            field=models.ForeignKey(limit_choices_to={'type__in': ['DISTRICT', 'NATIONAL']}, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.DeleteModel(
            name='TrainingCenter',
        ),
    ]
