# Generated by Django 5.2 on 2025-06-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_migrate_existing_courses'),
        ('institutions', '0002_institution_district_institution_ds_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
       
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Indicates if the course is free of charge'),
        ),
        migrations.AddField(
            model_name='course',
            name='non_nvq_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration for non-NVQ courses', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='non_nvq_duration_unit',
            field=models.CharField(blank=True, choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Unit for non-NVQ course duration', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nvq3_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration for NVQ Level 3', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nvq3_duration_unit',
            field=models.CharField(blank=True, choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Unit for NVQ Level 3 duration', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nvq4_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration for NVQ Level 4', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nvq4_duration_unit',
            field=models.CharField(blank=True, choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Unit for NVQ Level 4 duration', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nvq_level',
            field=models.CharField(choices=[('none', 'None-NVQ'), ('nvq3', 'NVQ Level 3'), ('nvq4', 'NVQ Level 4'), ('both', 'Both NVQ 3 & 4')], default='none', help_text='NVQ Level of the course', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='training_type',
            field=models.CharField(choices=[('cbt', 'Center Based Training'), ('ebt', 'Enterprise Based Training'), ('both', 'Both CBT & EBT')], default='cbt', help_text='Type of training provided', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for the course', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Registration fee for the course', max_digits=10),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='institution',
            field=models.ForeignKey(limit_choices_to={'type__in': ['DISTRICT', 'NATIONAL']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order'],
            },
        ),
    ]
