# Generated by Django 5.2 on 2025-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_content_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_unit',
        ),
        migrations.AddField(
            model_name='course',
            name='certification_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certification_si',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='features_en',
            field=models.JSONField(default=list, help_text='List of course features', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='features_si',
            field=models.JSONField(default=list, help_text='List of course features', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements_en',
            field=models.JSONField(default=list, help_text='List of entry qualifications', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements_si',
            field=models.JSONField(default=list, help_text='List of entry qualifications', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_si',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='description_si',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='name_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='title_si',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='description_si',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='title_si',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='active_learners_en',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='active_learners_si',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='proud_graduates_en',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='proud_graduates_si',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='total_courses_en',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='total_courses_si',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button_text_en',
            field=models.CharField(default='Register Now', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button_text_si',
            field=models.CharField(default='Register Now', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='description_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='title_si',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='name_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_si',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
