# Generated by Django 5.2 on 2025-06-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_duration_remove_course_duration_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontent',
            name='background_image',
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hero_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.herocontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
