# Generated by Django 5.2 on 2025-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
