# Generated by Django 5.2 on 2025-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newscategory_name_en_newscategory_name_si_and_more'),
    ]

    operations = [
      
      
    ]
