# Generated by Django 5.2 on 2025-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscategory_name_en_newscategory_name_si_and_more'),
    ]

    operations = [
       
      
    ]
