# Generated by Django 5.2 on 2025-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newscategory_name_en_newscategory_name_si_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_si',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='description_si',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_si',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
